### PR TITLE
reimplement burnwire burn interval with config file parameter

### PR DESCRIPTION
**Pull request by msalinoh**

### CODE REVIEW

**Comment by MattCummings0517** [comment]
This looks OK to me.  Just wondering if you tested it out on the bench.

**Comment by msalinoh** [comment]
It was tested on hardware prior to making a pull request. I used the config file to set the timeout and burn intervals to be short, and monitored the voltage across the burn wire to observe the expected changes.

**Comment by MattCummings0517** [comment]
Great.  I'm OK with the changes...are you able to do the merge or do I need to do it?

**Comment by msalinoh** [comment]
Yes, I will handle the merge.

**Pull request merged**
